# Generated by Django 4.2.2 on 2023-07-17 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_remove_post_subscribers_postcategory_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
